{
    'connections': {
        # Dict format for connection
        'default': {
            'engine': 'tortoise.backends.asyncmy',
            'credentials': {
                'host': '34.64.165.47',
                'port': '3306',
                'user': 'root',
                'password': 'qlrtm8146',
                'database': 'fastapi',
            }
        },
        # Using a DB_URL string
        'default': 'mysql://root:qlrtm8146@34.64.165.47:3306/fastapi'
    },
    'apps': {
        'models': {
            'models': ['models.models'],
            # If no default_connection specified, defaults to 'default'
            'default_connection': 'default',
        }
    }
}